- package-lock.json
- package.json
We got reports that using taquito and beacon resulted in two instances of `libsodium-wrappers` getting loaded. We should try co-ordinate to keep our packages dependency on `libsodium-wrappers` in sync.
> chore(deps) update libsodium to 0.7.8

- package.json
- src/utils/qr.ts
- tsconfig-cjs.json
- tsconfig.json
Hello! I'm currently using Beacon in a project that uses the [Snowpack](https://www.snowpack.dev/) build tool, which relies on native browser support for [ES Modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). I noticed some problems when importing Beacon as it currently only builds CommonJS modules.
Thankfully TypeScript makes compiling ES Modules alongside CommonJS builds pretty straightforward, so I made the following configuration changes which seem to resolve my issue and maintain compatibility with the existing build.
Let me know how this looks and whether I need to make additional changes to fully support each workflow.
Thanks!
> feat: Support ES Modules

- src/transports/PostMessageTransport.ts
- src/transports/clients/PostMessageClient.ts
- test/clients/dapp-client.spec.ts
- test/clients/wallet-client.spec.ts
- test/transports/post-message-transport.spec.ts
Fixes the sonarcloud "Origins should be verified during cross-origin communications" issue. https://rules.sonarsource.com/javascript/RSPEC-2819
> fix(postmessage): use specific identity instead of wildcard as recipient

- src/clients/beacon-client/BeaconClient.ts
- src/clients/beacon-client/BeaconClientOptions.ts
- src/clients/client/Client.ts
- src/clients/client/ClientOptions.ts
- src/clients/dapp-client/DAppClient.ts
- src/clients/dapp-client/DAppClientOptions.ts
- src/clients/wallet-client/WalletClient.ts
- src/clients/wallet-client/WalletClientOptions.ts
- src/transports/DappP2PTransport.ts
- src/transports/P2PTransport.ts
- src/transports/WalletP2PTransport.ts
- src/transports/clients/P2PCommunicationClient.ts
This PR does 2 things:
- Select default icons/logos for wallets that we have icons locally (eg. AirGap Wallet, Kukai, Beacon Extension)
- Include icons in pairing request/response
> feat(toast): include wallet icons for known wallets

- src/clients/dapp-client/DAppClient.ts
Tests are fixed in the parent branch
> fix(dapp-client): persist active peer after active account has been set

- example-wallet.html
- package-lock.json
- package.json
- src/clients/client/Client.ts
- src/constants.ts
- src/matrix-client/MatrixClient.ts
- src/matrix-client/MatrixClientEventEmitter.ts
- src/matrix-client/MatrixHttpClient.ts
- src/matrix-client/models/MatrixClientEvent.ts
- src/matrix-client/models/MatrixMessage.ts
- src/matrix-client/models/MatrixStateEvent.ts
- src/transports/P2PTransport.ts
- src/transports/Transport.ts
- src/transports/clients/P2PCommunicationClient.ts
- test/matrix-client/matrix-client.spec.ts
- test/transports/p2p-transport.spec.ts
This PR adds a couple of things:
- Disconnect capability on the P2P Transport. If this is called (eg. when calling .destroy() on the client), the polling is stopped and the current requests are cancelled.
- An "isConnected()" method was added to the MatrixClient. This is used to make sure that the login and initial sync with the matrix node has actually happened before we allow any public methods to be called. Without this change, messages would sometimes be sent before the login happened and would be lost.
- The "timestamp" of the message is now tracked and the last unhandled message that has happened before the login will be handled once the client is ready.
> feat(matrix): add stop method to cancel network requests

- example-dapp.html
- example-wallet.html
- package-lock.json
- package.json
- src/constants.ts
- src/matrix-client/MatrixClientEventEmitter.ts
- src/matrix-client/models/MatrixClientEvent.ts
- src/transports/Transport.ts
- src/transports/clients/P2PCommunicationClient.ts
- src/types/storage/StorageKey.ts
- src/types/storage/StorageKeyReturnDefaults.ts
- src/types/storage/StorageKeyReturnType.ts
- test/_helpers/_setup.spec.ts
- test/transports/p2p-transport.spec.ts
- test/transports/post-message-transport.spec.ts
Test Cases:
Tip: To simulate a server being down, simply edit the `beacon:matrix-selected-node` to a URL that does not have a beacon/matrix service running
> feat(p2p): improve reconnect behaviour

- scripts/generate-wallet-list.ts
- Adds the ability to have wallet logo images in the SVG format
- Some refactoring to use the promises version of `readFile` and `writeFile`
- Ran a build with an SVG image and the following entry was created.
```json
{
"key": "exodus_mobile",
"name": "Exodus Mobile",
"shortName": "Exodus Mobile",
"color": "",
"logo": "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjMwMCIgdmlld0JveD0iMCAwIDMwMCAzMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxwYXRoIGQ9Ik0yOTguMjAzIDgzLjc2NDVMMTcwLjQ0OSAwVjQ2LjgzMzJMMjUyLjQwNSAxMDAuMDg5TDI0Mi43NjMgMTMwLjU5OEgxNzAuNDQ5VjE2OS40MDJIMjQyLjc2M0wyNTIuNDA1IDE5OS45MTFMMTcwLjQ0OSAyNTMuMTY3VjMwMEwyOTguMjAzIDIxNi41MDNMMjc3LjMxMyAxNTAuMTM0TDI5OC4yMDMgODMuNzY0NVoiIGZpbGw9InVybCgjcGFpbnQwX2xpbmVhcl8xNjYxXzI5NSkiLz4KPHBhdGggZD0iTTU5LjMwM …
```
> feat: svg wallet logo images

- scripts/blockchains/tezos.ts
The Exodus mobile wallet with Beacon support has not yet been released and needs to be temporarily removed to assure no one attempts to use it.
> revert: temporarily remove Exodus mobile wallet

- assets/alert/alert.css
Removed conflicting styles for screens with height >700px
Before:
After:
Probably related: https://github.com/airgap-it/beacon-sdk/pull/406
> fix(ui): remove pairing alert overflow

- package-lock.json
- package.json
1. Use [NPM workspaces](https://docs.npmjs.com/cli/v9/using-npm/workspaces) instead of manually creating symbolic links.
2. Fixes the dependency versions in the `package-lock.json` from "^3.3.0" -> "^3.3.2"
From the NPM docs.
> This set of features makes up for a much more streamlined workflow handling linked packages from the local file system. Automating the linking process as part of npm install and avoiding manually having to use npm link in order to add references to packages that should be symlinked into the current node_modules folder.
- Ran unit tests and build successfully.
> feat: use npm workspaces

- Dockerfile
- lerna.json
- Copy all the source files to the `/app` directory because some files are needed during `npm install` which triggers a build via lerna
- Remove redundant build step since lerna is already taking care of that
- Set node env before install packages
> fix: docker and lerna fixes

- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
Fix sessions not overlapping.
The code that handled this logic treated the openSession and closeSession separately.
This caused a side effect whenever a user tried to abort a new sync request meanwhile the DApp already had a valid session set.
> fix: clear session

- examples/dapp.html
This PR should fix "Rejection of operation request with prepare delay will not show an aborted error"
> fix: removed ui reset onError

- packages/beacon-dapp/src/dapp-client/DAppClient.ts
This PR should solve "Rejection of operation request with prepare delay will not show an aborted error"
I haven't used the "PERMISSION_REQUEST_ERROR" toast, because during the very first initialisation phase `this.getWalletInfo()` won't return anything and therefore the toast message will appear broken.
> fix: added error modal

- packages/beacon-core/src/transports/Transport.ts
- packages/beacon-core/src/transports/clients/CommunicationClient.ts
- packages/beacon-core/src/transports/clients/MessageBasedClient.ts
- packages/beacon-dapp/src/dapp-client/DAppClient.ts
- packages/beacon-transport-matrix/src/communication-client/P2PCommunicationClient.ts
- packages/beacon-transport-postmessage/src/PostMessageClient.ts
- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
- packages/beacon-types/src/index.ts
- packages/beacon-types/src/types/P2PPairingRequest.ts
- packages/beacon-types/src/types/P2PPairingResponse.ts
- packages/beacon-types/src/types/PeerInfo.ts
- packages/beacon-types/src/types/PostMessagePairingRequest.ts
- packages/beacon-types/src/types/PostMessagePairingResponse.ts
- packages/beacon-types/src/types/WalletConnectPairingRequest.ts
- packages/beacon-types/src/types/WalletConnectPairingResponse.ts
- packages/beacon-wallet/src/client/WalletClient.ts
> fix: refactor PeerInfo typings

- packages/beacon-ui/src/utils/platform.ts
This should solve #585 
I added `DuckDuckGO Mobile` to the IOS group because it seems it has a built-in popup blocker like Safari and thus the code should behave the same.
> fix: duckduckgo browser pairing blocked

- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
- packages/beacon-ui/src/ui/alert/index.tsx
- packages/beacon-ui/src/utils/wallets.ts
This should fix #572
In order to make other pairing options appear (i.e "Pair with mobile"), you still need to add an object entry in one or more lists inside the `tezos.ts` file
> fix: web wallet no pairing choice modal

- packages/beacon-ui/src/ui/alert/index.tsx
In SolidJS, computations and cleanups should be created within a component that is being rendered. 
However with our approach only whatever is inside the `dispose` function is actually called with the `render` method.
To resolve this warning, you can wrap your component in a `createRoot` or `render` function.
> fix: computations warning

- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
> fix: disconnect rejection

- examples/dapp.html
- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
- Added queue to handle multiple messages
-  In example DApp overridden default behaviour for unhandled promise rejection
Assumption: The wallet handles requests with a FIFO priority
> fix: add queue for handling multiple messages UI

- packages/beacon-dapp/src/dapp-client/DAppClient.ts
- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
1. This PR addresses a potential bug that appears only when 2 or more tabs are open, and all of them have a paring modal open.
In this scenario when a tab successfully pairs with a wallet, the others also correctly sync thanks to broadcast channel. However, beacon enters a broken state when closing all the open alerts because, in the tabs that never concluded the sync, they still have a pending proposal.
2. WC's ping gets dropped after a delay oft 30s. Added interval to generate a new one after expiration.
> fix: WC bugs

- examples/abstracted-account.html
- examples/dapp.html
- packages/beacon-dapp/src/beacon-message-events.ts
- packages/beacon-dapp/src/dapp-client/DAppClient.ts
- packages/beacon-dapp/src/events.ts
- packages/beacon-types/src/index.ts
- packages/beacon-types/src/types/RequestSimulatedProofOfEventChallengeInput.ts
- packages/beacon-types/src/types/beacon/BeaconMessage.ts
- packages/beacon-types/src/types/beacon/BeaconMessageType.ts
- packages/beacon-types/src/types/beacon/BeaconRequestMessage.ts
- packages/beacon-types/src/types/beacon/messages/BeaconRequestInputMessage.ts
- packages/beacon-types/src/types/beacon/messages/BeaconRequestOutputMessage.ts
- packages/beacon-types/src/types/beacon/messages/BeaconResponseInputMessage.ts
- packages/beacon-types/src/types/beacon/messages/BeaconResponseOutputMessage.ts
- packages/beacon-types/src/types/beacon/messages/SimulatedProofOfEventChallengeRequest.ts
- packages/beacon-types/src/types/beacon/messages/SimulatedProofOfEventChallengeResponse.ts
- packages/beacon-wallet/src/interceptors/IncomingRequestInterceptor.ts
- packages/beacon-wallet/src/interceptors/OutgoingResponseInterceptor.ts
This PR adds the support for the [Tzip 28](https://gitlab.com/tezos/tzip/-/blob/a17642ac67c26744a864e67645705b0de3d98ff3/drafts/current/draft-simulated-proof-of-event/tzip-28.md): Simulated Proof of Event.
This PR fix the build fails with the PR https://github.com/airgap-it/beacon-sdk/pull/692 (related to this https://github.com/airgap-it/beacon-sdk/pull/731#issuecomment-1988764311)
@IsaccoSordo @AndreasGassmann please ping me if there is another issue with this PR, thanks.
> [Feat] Tzip 28 support with build fixed

- packages/beacon-dapp/src/dapp-client/DAppClient.ts
The red highlighted line of code caused signClient to throw a 'No matching key: expirer' error
> fix: double disconnect

- examples/dapp.html
- packages/beacon-core/src/clients/client/Client.ts
- packages/beacon-dapp/src/dapp-client/DAppClient.ts
- packages/beacon-transport-walletconnect/src/WalletConnectTransport.ts
- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
- packages/beacon-utils/src/utils/crypto.ts
- packages/beacon-wallet/src/client/WalletClient.ts
This PR addresses multiple instances of failed subscriptions cleanup in Beacon; also there is no need to undergo a big refactor.
Namely I found 3 issues:
1. The `Client` instance once it had subscribed to the transport, it never cleared its subscriptions. Now we keep track of each subscription and remove each one of them on Client destroy (this needs to be managed on the client instance not on the transport one)
2. WalletConnectCommunication client never cleared its subscriptions maps when closing the client
3. Because we are subscribing to WC session events, DAppClient wouldn’t behave correctly while receiving an event (`session_update` for instance) because our logic assumed that we would have always end up in a one direction flow (one request from the dApp, one response from the …
> Fix: subscription management

- packages/beacon-dapp/src/utils/tzkt-blockexplorer.ts
- packages/beacon-transport-matrix/src/communication-client/P2PCommunicationClient.ts
With two or more tabs open, disconnecting and reconnecting on one would have cause all the other tabs to enter an almost endless loop while trying to join the room.
> fix: multitab send

- packages/beacon-dapp/src/utils/tzkt-blockexplorer.ts
- packages/beacon-types/src/types/beacon/NetworkType.ts
- packages/beacon-types/src/types/ui.ts
- scripts/blockchains/tezos-sapling.ts
- scripts/blockchains/tezos.ts
Paris protocol was launched recently for tezos blockchain. Tzkt already has launched [website](https://parisnet.tzkt.io) to support it. Need to include it in beacon sdk to access through the SDK using NetworkTypes
> Add support for newly launched parisnet in tezos protocol.

- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
The goal of handling both the account address and its public key within the same `session_update` is to prevent a `fetchAccounts` call, which can lead to undesired behaviors (as noted in issue #765).
With the changes in #782, a wallet can send only the public key, allowing Beacon to resolve the account's address independently.
However, to ensure backward compatibility with previous Beacon versions, the changes introduced in this PR are beneficial. Developers can still send the account address in the first position of the accounts array and the public key in the second position, thereby avoiding the `fetchAccounts` call.
> Feat: session update account address and pbk

- packages/beacon-dapp/src/dapp-client/DAppClient.ts
- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
Resolved a stuck state that occurred after disconnecting a dApp while waiting for a response from the wallet, and then tried to sync.
> fix: disconnect stuck state

- packages/beacon-types/src/types/tezos/operations/Origination.ts
What:
Changed the type of `TezosOriginationOperation.script` from `string` to `ScriptedContracts`.
Why:
The `string` type doesn't match the [Tezos RPC specification](https://tezos.gitlab.io/shell/p2p_api.html#origination-tag-109).
Details:
The Origination operation has a `script` field with the following parameters: ([doc](https://tezos.gitlab.io/shell/p2p_api.html#origination-tag-109))
- `size`: determined from data
- `contents`: `$alpha.scripted.contracts` 
The `ScriptedContracts` type is matching the definition of $alpha.scripted.contracts ([doc](https://tezos.gitlab.io/shell/p2p_api.html#alpha-scripted-contracts))
- `# bytes in next field`, 4 bytes, unsigned 30-bit big-endian integer
- `code`, Variable, bytes
- `# bytes in next field`, 4 bytes, unsigned 30-bit big-endian integer
- …
> fix: ScriptedContracts in Origination

- packages/beacon-types/src/index.ts
Adding `TezosPreEndorsementOperation` to the list of exported types.
This is the only type in `PartialTezosOperation` which is not exported.
> fix: export for TezosPreEndorsementOperation
