airgap-it/beacon-sdk

- example-dapp.html
- src/clients/dapp-client/DAppClient.ts
- src/errors/BeaconError.ts
- src/events.ts
closes https://github.com/airgap-it/beacon-sdk/issues/94
> fix(promise): rejected promises were rejected internally in some cases

- example-dapp.html
- src/clients/dapp-client/DAppClient.ts
- src/events.ts
- src/ui/toast/Toast.ts
First point in https://github.com/airgap-it/beacon-sdk/issues/196
> feat(ui): add prepare state and methods

- assets/alert/alert-pair.css
- assets/alert/alert-pair.html
- assets/alert/alert.css
- example-dapp.html
- src/clients/dapp-client/DAppClient.ts
- src/clients/dapp-client/DAppClientOptions.ts
- src/events.ts
- src/ui/alert/Alert.ts
- src/ui/alert/PairingAlert.ts
https://github.com/airgap-it/beacon-sdk/issues/212
> Draft: feat(disclaimer): add option to pass a disclaimer

- packages/beacon-transport-matrix/src/matrix-client/EventEmitter.ts
- packages/beacon-transport-matrix/src/matrix-client/MatrixClient.ts
- packages/beacon-transport-matrix/src/matrix-client/MatrixClientEventEmitter.ts
Fixes https://github.com/airgap-it/beacon-sdk/issues/277
> fix(): add event emitter and remove node dependency

- packages/beacon-ui/src/utils/qr.ts
- tsconfig.json
> allowSyntheticDefaultImports, resolve qrcode issue with rollup

- packages/beacon-ui/src/components/toast/index.tsx
- packages/beacon-ui/src/components/toast/styles.css
- packages/beacon-ui/src/ui/alert/index.tsx
- packages/beacon-ui/src/utils/platform.ts
Hi @jsamol,
I made the toast draggable, this should solve #193
The fix is intended only for desktop and not for mobile
> feat: made toast draggable

- packages/beacon-core/src/clients/beacon-client/BeaconClient.ts
- packages/beacon-core/src/index.ts
- packages/beacon-core/src/transports/Transport.ts
- packages/beacon-core/src/transports/clients/ClientEvents.ts
- packages/beacon-core/src/transports/clients/CommunicationClient.ts
- packages/beacon-dapp/src/dapp-client/DAppClient.ts
- packages/beacon-dapp/src/events.ts
- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
This PR should solve #461, #487, #489, #510 and #518
> Added event propagation to the transport layer

- packages/beacon-dapp/src/dapp-client/DAppClient.ts
> fix: added optional check

- packages/beacon-core/src/managers/PermissionManager.ts
> fix: added senderId in addPermission check

- packages/beacon-core/src/utils/Logger.ts
- packages/beacon-dapp/src/dapp-client/DAppClient.ts
> feat: added time and timeLog for Logger

- packages/beacon-types/src/index.ts
> feat: Exported micheline michelson v1 expression type

- packages/beacon-dapp/src/dapp-client/DAppClient.ts
- packages/beacon-dapp/src/events.ts
- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
- packages/beacon-wallet/src/client/WalletClient.ts
- packages/beacon-wallet/src/interceptors/IncomingRequestInterceptor.ts
- packages/beacon-wallet/src/interceptors/OutgoingResponseInterceptor.ts
This should solve [#2613](https://github.com/ecadlabs/taquito/issues/2613)
> fix: updated console.log to logger.log

- e2e/permission-request.ts
- package-lock.json
- package.json
- packages/beacon-dapp/__tests__/p2p-transport.spec.ts
- packages/beacon-ui/src/components/qr/index.tsx
- packages/beacon-ui/src/components/toast/index.tsx
- packages/beacon-ui/src/components/top-wallets/index.tsx
- packages/beacon-ui/src/components/wallets/index.tsx
- packages/beacon-ui/src/ui/alert/index.tsx
- tsconfig.json
After the PR is merged, I will rebase the feat/transport-kukai-wc2
> fix: typedoc

- packages/beacon-ui/src/ui/alert/index.tsx
- scripts/blockchains/tezos.ts
> fix: removed hard coded link

- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
> fix: duplicated session

- packages/beacon-dapp/src/dapp-client/DAppClient.ts
> fix: destroy

- packages/beacon-dapp/src/utils/tzkt-blockexplorer.ts
- packages/beacon-types/src/types/beacon/NetworkType.ts
- scripts/blockchains/tezos-sapling.ts
- scripts/blockchains/tezos.ts
because it will start on wednesdays
> mondaynet is renamed to weeklynet

- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
This PR addresses a missing ack UI toast notification reported in #620
> fix: ack notification missing

- packages/beacon-core/src/transports/clients/ClientEvents.ts
- packages/beacon-dapp/src/dapp-client/DAppClient.ts
- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
Add pending toast and rejection on init
> fix: add back ack event

- packages/beacon-ui/src/components/toast/index.tsx
- packages/beacon-ui/src/components/toast/styles.css
Fixed toast resizing, a min width and height are set to avoid the toast from collapsing
This PR addresses: #663
> fix: toast collapse

- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
Added check to avoid race condition on multiple sessions approval
> fix: session check

- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
> fix: accounts check

- scripts/blockchains/tezos.ts
This reverts commit b37d0ffaa130f7200ea132d27854557508996bac.
This PR addresses #680
> Revert "fix: removed galleon"

- packages/beacon-core/src/transports/clients/CommunicationClient.ts
- packages/beacon-dapp/src/dapp-client/DAppClient.ts
- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
- packages/beacon-ui/src/index.ts
- packages/beacon-ui/src/ui/alert/index.tsx
Add app switching functionality
> fix: add app switching

- packages/beacon-ui/src/ui/alert/index.tsx
- scripts/blockchains/tezos.ts
Added possibility to pair with either kukai mobile and web on mobile
> feat: add selection form

- packages/beacon-ui/src/ui/alert/index.tsx
Init hybrid transport for kukai (web: p2p, mobile: WC)
> fix: init hybrid transport

- packages/beacon-dapp/src/dapp-client/DAppClient.ts
- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
Fixed issue causing the wrong transport to be closed
> Fix: expirer

- packages/beacon-dapp/src/dapp-client/DAppClient.ts
- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
Fix: disconnection after 5 minutes
> fix: pairing expired

- packages/beacon-dapp/src/dapp-client/DAppClient.ts
- packages/beacon-dapp/src/events.ts
URL update to reference the new migration guide in the docs
> chore: url update

- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
> fix: commented clearCache

- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
This PR addresses https://github.com/airgap-it/beacon-sdk/issues/745
> fix: wallet connect no matching key

- packages/beacon-core/src/storage/IndexedDBStorage.ts
- packages/beacon-core/src/storage/WCStorage.ts
- packages/beacon-dapp/src/dapp-client/DAppClient.ts
- packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts
- packages/beacon-ui/src/components/bug-report-form/index.tsx
> IndexedDB refactor

- packages/beacon-ui/src/components/info/styles.css
> fix: unit scaling

- packages/beacon-types/src/types/tezos/TezosTransactionParameters.ts
Aligned with Tezos P2P API:
https://tezos.gitlab.io/shell/p2p_api.html#alpha-entrypoint-determined-from-data-8-bit-tag
> fix: aligned TezosTransactionParameters with Tezos p2p API
